### PR TITLE
Added CodeFile for Homescreen

### PR DESCRIPTION
**Pull request by geekswaroop**
I have added the C++ code for the Homescreen using opengl. But one of the functions, glutDisplayMode is not working on my system(I've tried debugging. They say it doesn't work on Linux etc.). Other than that, this file should be able to show text in the screen.

### CODE REVIEW

**Comment by shanthanu9** [comment]
@geekswaroop 
1. Avoid the use of sprintf_s (it's a Windows dependent function). You can directly initialise the buf with the string and then pass it to renderbitmap.
2. The screen width:height ratio seems off. Contact the group building the maze and match your screen size with theirs. Also, all the text is not being displayed on the screen. Experiment with different text sizes and try to get it right. 
3. You need to add an "Enter" key event handler. Use my 5th sample code for this. Google and check what macro is used for "enter" key for this.

**Comment by geekswaroop** [comment]
Yeah! Suggestions were implemented successfully. The only messy part is Special Key function. I just have written the code for event handling. The rest has to be integrated by the Maze team. I have dry tested it. It works just fine. Also, all the text is within the window now!

**Comment by rohit-mp** [comment]
@geekswaroop 
- Could you change the font of the text to make it look somewhat more block type so that it matches with the game and format the text with indents and newlines?
- You're checking for the space key right now instead of the enter key. So change either the instructions or the switch case.
- Could you also maybe display a dummy layout when the key is pressed so that it's easier for integration to the next screen?

**Comment by shanthanu9** [comment]
ascii for 'enter' is 13. Also after clicking enter, the same screen is being displayed!! U will need to write another dummy dispay() to verify

**Pull request closed without merging**
