### PR TITLE
Added code for Smart troll

### PR DESCRIPTION
**Pull request by Shree987**

### CODE REVIEW

**Comment by shanthanu9** [comment]
Could a send a working 2d ascii game? That way it will be easier for me to check if your logic is correct. Currently, I am not able to compile your code and test it.

**Comment by shanthanu9** [comment]
#### Trolls Disappear!!
Screenshot from 2019-03-10 10-28-48
Two trolls dissappear in the next move!
Screenshot from 2019-03-10 10-28-56

They come back up again later. This issue might be due to trolls colliding or hitting walls. Check this.

**Comment by rohit-mp** [comment]
@Shree987 what's the status?

**Comment by Shree987** [comment]
I corrected the code, please verify it once again

**Comment by rohit-mp** [comment]
@Shree987 Should the player touching the wall be considered as an illegal move and be neglected or result in losing the game?

**Comment by Shree987** [comment]
Touching the wall is considered to be resulting into losing the game.

**Review by rohit-mp — APPROVED** [review]

**Pull request merged**
