### PR TITLE
This contains the graphics part of the game for the maze and trolls

### PR DESCRIPTION
**Pull request by adharshkamath**
Use Up, Down, Right , Left Keys for movement.
The Green colored object is the player. The red colored ones are the trolls.
Press the 'home' button after the "WIN" or "LOSE" message is displayed, to exit the game.

### CODE REVIEW

**Comment by shanthanu9** [comment]
@adharshkamath 
1. Initially, the player is not seen until key press. Is this a feature or a bug?
2. Give brief documentation later for the code (after the review). Basically, write more comments for your code. This will make it reading code by someone else easier.
3. Again after the review, could u replace constants (like the number of trolls and dimensions of the maze) with macros? To avoid repeating code.

**Comment by adharshkamath** [comment]
@shanthanu9  
What's mentioned in 1. is actually a bug. I'm not able to figure out where it is. I'll try fixing it asap.
I'll make another file with comments and include an instructions file later. Regarding the macros, I'll make the necessary changes and submit another PR later.

**Comment by rohit-mp** [comment]
After displaying WIN or LOSE, the home button isn't very intuitive. So could you rather keep it as enter or spacebar?

**Comment by rohit-mp** [comment]
I'm not able to interact with the weapons (the yellow boxes)

**Comment by adharshkamath** [comment]
> I'm not able to interact with the weapons (the yellow boxes)

I'll get the weapons and phasable walls working by tomorrow

**Comment by rohit-mp** [comment]
what's the status?

**Comment by rohit-mp** [comment]
Looks awesome! Great work with the start screen and the extra features. I like how I can outrun the trolls now. A small suggestion I would make as a player is to make the instructions visual, in the sense instead of just telling yellow is a weapon, you could maybe put up a yellow box along with the instructions and tells that's how a weapon looks since, for a first time user, these many features will be hard to take care of. Also, include instructions about the teleporters.

**Comment by rohit-mp** [comment]
I have a few doubts too
- Am I supposed to die by touching the flaming wall or just by going near it?
- Why doesn't the troll touch me when I'm holding a weapon, instead just moves around me?

**Comment by adharshkamath** [comment]
> Looks awesome! Great work with the start screen and the extra features. I like how I can outrun the trolls now. A small suggestion I would make as a player is to make the instructions visual, in the sense instead of just telling yellow is a weapon, you could maybe put up a yellow box along with the instructions and tells that's how a weapon looks since, for a first time user, these many features will be hard to take care of. Also, include instructions about the teleporters.

Will do!

**Comment by rohit-mp** [comment]
Also, maybe don't let the game start until the player makes the first move? because I had some difficulty where I was :laughing:

**Comment by adharshkamath** [comment]
> I have a few doubts too
> 
> * Am I supposed to die by touching the flaming wall or just by going near it?
> * Why doesn't the troll touch me when I'm holding a weapon, instead just moves around me?

Yes. You die if you go to a block that's next to a fiery wall. 
Regarding the trolls, they try attacking you only if you don't have a weapon. The cases we've mentioned in the troll function so far, deal with only such scenarios. That's why they just move around you when you're armed. 
We'll add few more cases and make the troll attack in those situations also

**Comment by adharshkamath** [comment]
> Also, maybe don't let the game start until the player makes the first move? because I had some difficulty where I was

Will do!

**Comment by adharshkamath** [comment]
> Also, maybe don't let the game start until the player makes the first move? because I had some difficulty where I was

Will do!

**Pull request merged**
